# Generated by Django 5.0.7 on 2024-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='slot',
            field=models.CharField(default='', max_length=11, verbose_name='время записи'),
        ),
    ]
