# Generated by Django 5.0.7 on 2024-07-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='service_date',
            field=models.DateField(default=None, verbose_name='Дата процедуры'),
        ),
    ]
