# Generated by Django 5.0.7 on 2024-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_registration_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='master_services', to='bot.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service_date',
            field=models.DateField(verbose_name='Дата процедуры'),
        ),
    ]
