# Generated by Django 5.0.7 on 2024-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_registration_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='slot',
        ),
        migrations.AddField(
            model_name='registration',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Отправилось напоминание'),
        ),
    ]
