# Generated by Django 5.0.7 on 2024-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_client_master_service_salon_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Забронированный заказ', 'verbose_name_plural': 'Забронированные заказы'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедуры'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='master',
        ),
        migrations.AddField(
            model_name='master',
            name='salons',
            field=models.ManyToManyField(to='bot.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='bot.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес салона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя мастера'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='time_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название процедуры'),
        ),
    ]
