# Generated by Django 5.0.7 on 2024-07-27 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_registration_slot_registration_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата процедуры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='slot',
            field=models.CharField(default='', max_length=11, verbose_name='время записи'),
        ),
    ]
