# Generated by Django 5.0.7 on 2024-07-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_client_options_alter_master_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.salon', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='time_registration',
            field=models.DateTimeField(verbose_name='Время регистрации'),
        ),
    ]
