# Generated by Django 5.0.7 on 2024-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_master_services_and_more'),
        ('bot', '0003_alter_registration_service_date'),
    ]

    operations = [
    ]
