# Generated by Django 5.0.7 on 2024-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена'),
        ),
    ]
