# Generated by Django 5.0.7 on 2024-07-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Телеграмм id клиента'),
            preserve_default=False,
        ),
    ]
