# Generated by Django 5.0.7 on 2024-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_client_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
