# Generated by Django 5.0.7 on 2024-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_rename_phone_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Отправилось напоминание'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='time_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации'),
        ),
    ]
